doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            identity: IlyaPokamestov\ProductivitySuite\Library\DomainFramework\Infrastructure\Type\IdentityType
            consumer_id: IlyaPokamestov\ProductivitySuite\IDMS\Infrastructure\Persistence\Doctrine\Type\ConsumerIdType
            list_id: IlyaPokamestov\ProductivitySuite\Tasks\Infrastructure\Persistence\Doctrine\Type\ListIdType
            task_id: IlyaPokamestov\ProductivitySuite\Tasks\Infrastructure\Persistence\Doctrine\Type\TaskIdType
            owner_id: IlyaPokamestov\ProductivitySuite\Tasks\Infrastructure\Persistence\Doctrine\Type\OwnerIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            IDMS:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/IDMS/Domain'
                prefix: 'IlyaPokamestov\ProductivitySuite\IDMS\Domain'
                alias: IDMS
            Tasks:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Tasks/Domain'
                prefix: 'IlyaPokamestov\ProductivitySuite\Tasks\Domain'
                alias: Tasks
