framework:
    messenger:
        default_bus: event.bus
        buses:
            event.bus:
                default_middleware: allow_no_handlers
            # Better to split command / query busses to prevent uncontrolled crossing bounded context boundaries.
            # IDMS busses
            idms.command.bus:
                middleware:
                    - doctrine_transaction
            idms.query.bus:
            # Tasks busses
            tasks.command.bus:
                middleware:
                    - doctrine_transaction
            tasks.query.bus:
