framework:
    messenger:
        default_bus: event.bus
        buses:
            event.bus:
                default_middleware: allow_no_handlers
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus:
