nelmio_api_doc:
    documentation:
        info:
            title: Productivity Suite API
            description: Productivity Suite API in DDD with CQRS
            version: 1.0.0
        components:
            parameters:
                offsetParam: # Can be referenced via '#/components/parameters/offsetParam'
                    name: offset
                    in: query
                    description: Number of items to skip before returning the results.
                    required: false
                    schema:
                        type: integer
                        format: int32
                        minimum: 0
                        default: 0
                limitParam: # Can be referenced as '#/components/parameters/limitParam'
                    name: limit
                    in: query
                    description: Maximum number of items to return.
                    required: false
                    schema:
                        type: integer
                        format: int32
                        minimum: 1
                        maximum: 100
                        default: 20
#            headers:
#                AuthorizedConsumer:
#                    name: X-Authorized-Consumer-ID
#                    in: header
#                    schema:
#                        type: string
#                        format: uuid
#                    required: true
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
