# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    IlyaPokamestov\ProductivitySuite\Library\ApplicationFramework\:
        resource: '../src/Library/ApplicationFramework/'

    IlyaPokamestov\ProductivitySuite\IDMS\Infrastructure\:
        resource: '../src/IDMS/Infrastructure/'

    IlyaPokamestov\ProductivitySuite\Tasks\Infrastructure\:
        resource: '../src/Tasks/Infrastructure/'

    IlyaPokamestov\ProductivitySuite\IDMS\Domain\ConsumerRepository: '@IlyaPokamestov\ProductivitySuite\IDMS\Infrastructure\Doctrine\ConsumerRepository'
    IlyaPokamestov\ProductivitySuite\IDMS\Application\Query\ConsumerRepository: '@IlyaPokamestov\ProductivitySuite\IDMS\Infrastructure\Doctrine\ConsumerRepository'

    IlyaPokamestov\ProductivitySuite\Tasks\Domain\TaskList\ListRepository: '@IlyaPokamestov\ProductivitySuite\Tasks\Infrastructure\Doctrine\ListRepository'
    IlyaPokamestov\ProductivitySuite\Tasks\Application\Query\TaskList\ListRepository: '@IlyaPokamestov\ProductivitySuite\Tasks\Infrastructure\Doctrine\ListRepository'
    IlyaPokamestov\ProductivitySuite\Tasks\Domain\Task\TaskRepository: '@IlyaPokamestov\ProductivitySuite\Tasks\Infrastructure\Doctrine\TaskRepository'
    IlyaPokamestov\ProductivitySuite\Tasks\Application\Query\TaskRepository: '@IlyaPokamestov\ProductivitySuite\Tasks\Infrastructure\Doctrine\TaskRepository'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    IlyaPokamestov\ProductivitySuite\Library\DomainFramework\Infrastructure\DoctrineDomainEventsCollector:
        tags:
            - { name: doctrine.event_subscriber }

    # Buses configuration
    idms.command_handlers:
        namespace: IlyaPokamestov\ProductivitySuite\IDMS\Application\Command\
        resource: '../src/IDMS/Application/Command/*Handler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: idms.command.bus }

    idms.query_handlers:
        namespace: IlyaPokamestov\ProductivitySuite\IDMS\Application\Query\
        resource: '../src/IDMS/Application/Query/*Handler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: idms.query.bus }

    tasks.command_handlers:
        namespace: IlyaPokamestov\ProductivitySuite\Tasks\Application\Command\
        resource: '../src/Tasks/Application/Command/*/*Handler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: tasks.command.bus }

    tasks.query_handlers:
        namespace: IlyaPokamestov\ProductivitySuite\Tasks\Application\Query\
        resource: '../src/Tasks/Application/Query/*/*Handler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: tasks.query.bus }

    event_handlers:
        namespace: IlyaPokamestov\ProductivitySuite\
        resource: '../src/**/*EventHandler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: event.bus }

    # IDMS Controllers
    IlyaPokamestov\ProductivitySuite\IDMS\Presentation\REST\Controller\:
        resource: '../src/IDMS/Presentation/REST/Controller/'
        arguments:
            - '@idms.query.bus'
            - '@idms.command.bus'
        tags: [ 'controller.service_arguments' ]

    # Tasks Controllers
    IlyaPokamestov\ProductivitySuite\Tasks\Presentation\REST\Controller\:
        resource: '../src/Tasks/Presentation/REST/Controller/'
        arguments:
            - '@tasks.query.bus'
            - '@tasks.command.bus'
        tags: [ 'controller.service_arguments' ]
