imports:
    - { resource: services/idms.yaml }
    - { resource: services/tasks.yaml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    IlyaPokamestov\ProductivitySuite\DataFixtures\:
        resource: '../src/DataFixtures/'

    IlyaPokamestov\ProductivitySuite\Library\ApplicationFramework\:
        resource: '../src/Library/ApplicationFramework/'

    IlyaPokamestov\ProductivitySuite\Library\DomainFramework\:
        resource: '../src/Library/DomainFramework/'
        exclude:
            - '../../src/Library/DomainFramework/Application/'
            - '../../src/Library/DomainFramework/Domain/'
            - '../../src/Library/DomainFramework/Infrastructure/Type/'

    IlyaPokamestov\ProductivitySuite\Library\DomainFramework\Infrastructure\DoctrineDomainEventsCollector:
        tags:
            - { name: doctrine.event_subscriber }

    # Busses
    IlyaPokamestov\ProductivitySuite\Library\DomainFramework\Infrastructure\Messaging\CommandBusSymfonyMessengerAdapter:
        arguments:
            - '@command.bus'

    IlyaPokamestov\ProductivitySuite\Library\DomainFramework\Infrastructure\Messaging\QueryBusSymfonyMessengerAdapter:
        arguments:
            - '@query.bus'

    IlyaPokamestov\ProductivitySuite\Library\DomainFramework\Application\Messaging\CommandBusInterface: '@IlyaPokamestov\ProductivitySuite\Library\DomainFramework\Infrastructure\Messaging\CommandBusSymfonyMessengerAdapter'
    IlyaPokamestov\ProductivitySuite\Library\DomainFramework\Application\Messaging\QueryBusInterface: '@IlyaPokamestov\ProductivitySuite\Library\DomainFramework\Infrastructure\Messaging\QueryBusSymfonyMessengerAdapter'
    IlyaPokamestov\ProductivitySuite\Library\DomainFramework\Application\Messaging\EventBusInterface: '@IlyaPokamestov\ProductivitySuite\Library\DomainFramework\Infrastructure\Messaging\EventBusSymfonyMessengerAdapter'
