name: Pull Request Verification
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
      - name: Pull Request Assigner
        uses: thomaseizinger/assign-pr-creator-action@v1.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
